### ISSUE TITLE
Get a working script (Prettier)

### ISSUE THREAD

**Issue by GuillaumeAmat** [GuillaumeAmat/knuckle#1]
- [x] Set a dumb default configuration (not the final one)
- [x] Call `knuckle prettier` from a parent project and get that default config working on the parent project source code
- [x] Handle --write parameter
- [x] Handle .prettierignore
- Be able to override the default config with another one in the parent project (moved to #4)

**Comment by frosato-ekino** [comment]
@GuillaumeAmat In my opinion override capabilities should not be part of the MVP in a sense that it's not needed to make knuckle works. If our tool does only prettier and support an override, the benefits of our tool are limited (the users would rather install prettier directly). But if we support linting, code formatting, testing, with no configuration (or override) the service is limited but in my opinion more valuable. Our Minimal Viable Product should be a tool that does many things in a single manner rather than one thing in many manners, don't you think?

**Comment by GuillaumeAmat** [comment]
@frosato-ekino You're right it makes sense! I'll create a new kanban for the next version and move that issue into it 👍

**Comment by frosato-ekino** [comment]
@GuillaumeAmat This was actually easier than i thought if we support only one file format. check MR https://github.com/GuillaumeAmat/knuckle/pull/10
